/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic.tac.toe;
import java.awt.Color;

/**
 *
 * @author iam-v0id(SUHAAS KORAMPALLY)
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        btnng = new javax.swing.JButton();
        btnrst = new javax.swing.JButton();
        lblo = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        lbltie = new javax.swing.JTextField();
        lbltiew = new javax.swing.JTextField();
        lblxw = new javax.swing.JTextField();
        lblx = new javax.swing.JTextField();
        lblow = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 200, 94));

        btn4.setBackground(new java.awt.Color(255, 241, 118));
        btn4.setFont(new java.awt.Font("Comic Sans MS", 1, 84)); // NOI18N
        btn4.setForeground(new java.awt.Color(172, 8, 0));
        btn4.setMaximumSize(new java.awt.Dimension(33, 33));
        btn4.setMinimumSize(new java.awt.Dimension(33, 33));
        btn4.setOpaque(false);
        btn4.setPreferredSize(new java.awt.Dimension(33, 33));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 241, 118));
        btn7.setFont(new java.awt.Font("Comic Sans MS", 1, 84)); // NOI18N
        btn7.setForeground(new java.awt.Color(172, 8, 0));
        btn7.setMaximumSize(new java.awt.Dimension(33, 33));
        btn7.setMinimumSize(new java.awt.Dimension(33, 33));
        btn7.setOpaque(false);
        btn7.setPreferredSize(new java.awt.Dimension(33, 33));
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 241, 118));
        btn1.setFont(new java.awt.Font("Comic Sans MS", 1, 84)); // NOI18N
        btn1.setForeground(new java.awt.Color(172, 8, 0));
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setMaximumSize(new java.awt.Dimension(33, 33));
        btn1.setMinimumSize(new java.awt.Dimension(33, 33));
        btn1.setOpaque(false);
        btn1.setPreferredSize(new java.awt.Dimension(33, 33));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 241, 118));
        btn5.setFont(btn1.getFont());
        btn5.setForeground(new java.awt.Color(172, 8, 0));
        btn5.setMaximumSize(new java.awt.Dimension(33, 33));
        btn5.setMinimumSize(new java.awt.Dimension(33, 33));
        btn5.setOpaque(false);
        btn5.setPreferredSize(new java.awt.Dimension(33, 33));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 241, 118));
        btn8.setFont(btn1.getFont());
        btn8.setForeground(new java.awt.Color(172, 8, 0));
        btn8.setMaximumSize(new java.awt.Dimension(33, 33));
        btn8.setMinimumSize(new java.awt.Dimension(33, 33));
        btn8.setOpaque(false);
        btn8.setPreferredSize(new java.awt.Dimension(33, 33));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 241, 118));
        btn2.setFont(btn1.getFont());
        btn2.setForeground(new java.awt.Color(172, 8, 0));
        btn2.setMaximumSize(new java.awt.Dimension(33, 33));
        btn2.setMinimumSize(new java.awt.Dimension(33, 33));
        btn2.setOpaque(false);
        btn2.setPreferredSize(new java.awt.Dimension(33, 33));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnng.setBackground(new java.awt.Color(196, 28, 0));
        btnng.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnng.setText("New Game");
        btnng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnngActionPerformed(evt);
            }
        });

        btnrst.setBackground(new java.awt.Color(196, 28, 0));
        btnrst.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnrst.setText("Reset");
        btnrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrstActionPerformed(evt);
            }
        });

        lblo.setEditable(false);
        lblo.setBackground(new java.awt.Color(255, 249, 196));
        lblo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblo.setForeground(new java.awt.Color(135, 0, 0));
        lblo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblo.setText("O-wins");
        lblo.setToolTipText("");
        lblo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbloActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 241, 118));
        btn6.setFont(btn1.getFont());
        btn6.setForeground(new java.awt.Color(172, 8, 0));
        btn6.setMaximumSize(new java.awt.Dimension(33, 33));
        btn6.setMinimumSize(new java.awt.Dimension(33, 33));
        btn6.setOpaque(false);
        btn6.setPreferredSize(new java.awt.Dimension(33, 33));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 241, 118));
        btn9.setFont(btn1.getFont());
        btn9.setForeground(new java.awt.Color(172, 8, 0));
        btn9.setMaximumSize(new java.awt.Dimension(33, 33));
        btn9.setMinimumSize(new java.awt.Dimension(33, 33));
        btn9.setOpaque(false);
        btn9.setPreferredSize(new java.awt.Dimension(33, 33));
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 241, 118));
        btn3.setFont(btn1.getFont());
        btn3.setForeground(new java.awt.Color(172, 8, 0));
        btn3.setMaximumSize(new java.awt.Dimension(33, 33));
        btn3.setMinimumSize(new java.awt.Dimension(33, 33));
        btn3.setOpaque(false);
        btn3.setPreferredSize(new java.awt.Dimension(33, 33));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        lbltie.setEditable(false);
        lbltie.setBackground(new java.awt.Color(255, 249, 196));
        lbltie.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lbltie.setForeground(new java.awt.Color(135, 0, 0));
        lbltie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbltie.setText("Draw");
        lbltie.setToolTipText("");
        lbltie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltieActionPerformed(evt);
            }
        });

        lbltiew.setEditable(false);
        lbltiew.setBackground(new java.awt.Color(255, 249, 196));
        lbltiew.setFont(new java.awt.Font("Comic Sans MS", 1, 69)); // NOI18N
        lbltiew.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbltiew.setText("0");
        lbltiew.setToolTipText("");
        lbltiew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltiewActionPerformed(evt);
            }
        });

        lblxw.setEditable(false);
        lblxw.setBackground(new java.awt.Color(255, 249, 196));
        lblxw.setFont(new java.awt.Font("Comic Sans MS", 1, 69)); // NOI18N
        lblxw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblxw.setText("0");
        lblxw.setToolTipText("");
        lblxw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblxwActionPerformed(evt);
            }
        });

        lblx.setEditable(false);
        lblx.setBackground(new java.awt.Color(255, 249, 196));
        lblx.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblx.setForeground(new java.awt.Color(135, 0, 0));
        lblx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblx.setText("X-wins");
        lblx.setToolTipText("");
        lblx.setCaretColor(new java.awt.Color(230, 200, 94));
        lblx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblxActionPerformed(evt);
            }
        });

        lblow.setEditable(false);
        lblow.setBackground(new java.awt.Color(255, 249, 196));
        lblow.setFont(new java.awt.Font("Comic Sans MS", 1, 69)); // NOI18N
        lblow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblow.setText("0");
        lblow.setToolTipText("");
        lblow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltie)
                            .addComponent(btnng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblow)
                            .addComponent(lblxw)
                            .addComponent(btnrst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lbltiew, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnng, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(btnrst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblxw, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblow, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltie, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lbltiew, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnng, btnrst});

        btn7.getAccessibleContext().setAccessibleParent(btn7);

        pack();
    }// </editor-fold>                        
    public int curr=1,gameover=0;
    public int prev=curr,clicks=0;               
    public String checkWin()
    {
        if(btn1.getText().equals(btn2.getText()) && btn1.getText().equals(btn3.getText()) && !btn1.getText().equals(""))
            return (btn1.getText());
        if(btn4.getText().equals(btn5.getText()) && btn4.getText().equals(btn6.getText()) && !btn4.getText().equals(""))
            return (btn4.getText());
        if(btn7.getText().equals(btn8.getText()) && btn7.getText().equals(btn9.getText()) && !btn7.getText().equals(""))
            return (btn7.getText());
        if(btn1.getText().equals(btn4.getText()) && btn1.getText().equals(btn7.getText()) && !btn1.getText().equals(""))
            return (btn1.getText());
        if(btn2.getText().equals(btn5.getText()) && btn2.getText().equals(btn8.getText()) && !btn2.getText().equals(""))
            return (btn2.getText());
        if(btn3.getText().equals(btn6.getText()) && btn3.getText().equals(btn9.getText()) && !btn3.getText().equals(""))
            return (btn3.getText());
        if(btn1.getText().equals(btn5.getText()) && btn1.getText().equals(btn9.getText()) && !btn1.getText().equals(""))
            return (btn1.getText());
        if(btn3.getText().equals(btn5.getText()) && btn3.getText().equals(btn7.getText()) && !btn3.getText().equals(""))
            return (btn3.getText());        
        return "";
    }
    void doAction(javax.swing.JButton btn)
    {
        if(!btn.getText().isEmpty() || gameover==1)
            return;
        ++clicks;
        if(curr==1)
            btn.setText("X");
        else
            btn.setText("O");
        curr=(~curr);
        String winner=checkWin();
        if(!winner.isEmpty())
        {
            lbl1.setText(winner+ " Wins!");
            if(winner.equals("X"))
            {
                int curr_score=Integer.parseInt(lblxw.getText());
                lblxw.setText((curr_score+1)+"");
            }
            else
            {
                int curr_score=Integer.parseInt(lblow.getText());
                lblow.setText((curr_score+1)+"");
            }
            gameover=1;
        }
        else if(clicks==9)
        {
            lbl1.setText("Draw :)");
            int curr_score=Integer.parseInt(lbltiew.getText());
            lbltiew.setText((curr_score+1)+"");
            gameover=1;
        }
    }
    
    void newgame()
    {
        gameover=0;
        curr=~prev;
        prev=curr;
        clicks=0;
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        lbl1.setText("");
    }
    
    void reset()
    {
        newgame();
        lblxw.setText("0");
        lblow.setText("0");
        lbltiew.setText("0");
    }
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        // TODO add your handling code here:
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        // TODO add your handling code here:
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     


        // TODO add your handling code here:
    }                                    

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    
    
    
    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn1);
    }                                 

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn2);
    }                                 

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn4);
    }                                 

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn5);
    }                                 

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn7);
    }                                 

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn8);
    }                                 


    private void btnngActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        newgame();
    }                                     

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn6);
    }                                 

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {                                  
        doAction(btn9);
    }                                 

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        doAction(btn3);
    }                                 

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void lblxwActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btnrstActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        reset();
    }                                      

    private void lbltiewActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void lblowActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void lbltieActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void lbloActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void lblxActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               NewJFrame jfm=new NewJFrame();
               jfm.setVisible(true);
               jfm.getContentPane().setBackground(new Color(255, 209, 73));
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnng;
    private javax.swing.JButton btnrst;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField lblo;
    private javax.swing.JTextField lblow;
    private javax.swing.JTextField lbltie;
    private javax.swing.JTextField lbltiew;
    private javax.swing.JTextField lblx;
    private javax.swing.JTextField lblxw;
    // End of variables declaration                   
}
